dovecot_config_version = 2.4.0
dovecot_storage_version = 2.4.0

protocols = imap
listen = *
base_dir = /run/dovecot

ssl = required
ssl_server_cert_file = /etc/dovecot/tls/dovecot.crt
ssl_server_key_file = /etc/dovecot/tls/dovecot.key
ssl_min_protocol = TLSv1.2

auth_allow_cleartext = no
auth_mechanisms = plain login

mail_uid = vmail
mail_gid = vmail
first_valid_uid = 100
mail_home = /srv/mail/%{user}
mail_driver = maildir
mail_path = /srv/mail/%{user}/Maildir

passdb passwd-file {
  default_password_scheme = PLAIN
  passwd_file_path = /run/dovecot/users
}

userdb passwd-file {
  passwd_file_path = /run/dovecot/users
}

service imap-login {
  inet_listener imaps {
    port = 993
    ssl = yes
  }

  inet_listener imap {
    port = 0
  }
}

namespace inbox {
  inbox = yes
}

log_path = /dev/stderr
info_log_path = /dev/stdout
